# Generated by Django 4.0.4 on 2022-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingConnection',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('broker_ip', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('topic', models.CharField(max_length=60)),
                ('client_id', models.CharField(default='python-mqtt-89', editable=False, max_length=7)),
                ('username', models.CharField(default='emqx', max_length=30)),
                ('password', models.CharField(default='public', max_length=30)),
                ('message', models.CharField(default='', editable=False, max_length=60)),
            ],
        ),
    ]
