# Generated by Django 4.0.4 on 2022-05-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingMqtt', '0003_alter_settingmqtt_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingmqtt',
            name='code',
        ),
        migrations.AlterField(
            model_name='settingmqtt',
            name='client_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
